# kernel makefile

CC = gcc -std=c99
CXX = g++ -std=c++11

CFLAGS = -m64 -O2 -ffreestanding -nostdlib -mno-red-zone
CXXFLAGS = -m64 -O2 -ffreestanding -nostdlib -fno-exception -fno-rtti -mno-red-zone -mcmodel=kernel

.PHONY: all

all: kernel.a

kernel.a:

