#include <stdio.h>

int main(int argc, char *argv[])
{
	FILE *infp, *outfp;
	char c;
	unsigned count;
	
	if (argc != 4) {
		printf("Wrong number of arguments.\nUsage: %s outfile infile name\n", argv[0]);
		return -1;
	}
	
	infp = fopen(argv[2], "rb");
	if (infp == NULL) {
		printf("Cannot open input file %s!\n", argv[2]);
		return -1;
	}
	
	outfp = fopen(argv[1], "w");
	
	fprintf(outfp, "/*\n *\t%s\n *\n *\tthis file is auto generated by bin2c from file %s.\n */\n", argv[1], argv[2]);
	fprintf(outfp, "const char %s[] = {", argv[3]);
	
	count = 0;
	while (!feof(infp)) {
		int err = fread(&c, sizeof(c), 1, infp);
		if (err != 1)
			break;
		if (count)
			fprintf(outfp, ", ");
		if (count % 8 == 0)
			fprintf(outfp, "\n\t");
		fprintf(outfp, "0x%02x", c & 0xff);
		count++;
	}
	
	fprintf(outfp, "\n};\n");
	
	fclose(infp);
	fclose(outfp);
	
	return 0;
}